FROM mysql:5.7

MAINTAINER Steven Taylor <taylorsj1980@gmail.com>

#   Add environment variables
ENV MYSQL_DATABASE example_db
ENV MYSQL_ALLOW_EMPTY_PASSWORD yes

#   Import the DB data
#TODO

#   Expose ports
EXPOSE 3306
